In [3]:
import pandas as pd

In [4]:
dd=pd.read_csv("datasets/LMS_Dirty_Dataset (1).csv")
dd

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [6]:
print(dd.head(10))

   student_id student_name             course        city  age  gender  \
0           1         Gita         MERN Stack   Kathmandu   17  Female
1           2        Nabin       Data Science     Itahari   29  Female
2           3         Gita         MERN Stack      Dharan   20  Female
3           4         Gita  Digital Marketing     Itahari   20  Female
4           5         Gita       Data Science     Itahari   19    Male
5           6       Anisha       Data Science      Dharan   18    Male
6           7        Suman         MERN Stack      Dharan   33  Female
7           8         Sita         MERN Stack     Pokhara   28  Female
8           9         Gita            Flutter  Biratnagar   31    Male
9          10         Sita            Flutter      Dharan   25  Female

  enrollment_date  course_fee  discount payment_status  attendance_percent  \
0      2026-02-24       10000        10        Pending                73.0
1      2026-06-29       10000        20        Pending                68.0
2      2026-02-20        5000        20           Paid                71.0
3      2026-05-23        7000         0        Pending                88.0
4      2026-05-28        5000         0        Pending               100.0
5      2026-04-30        7000        10           Paid                57.0
6      2026-05-03        5000         0           Paid                52.0
7      2026-06-23        5000        20        Pending                71.0
8      2026-05-06       -5000        10        Pending                70.0
9      2026-01-15        5000        20        Pending                53.0

   assignment_score  final_score  rating     mentor       phone  \
0                46           98       5  Samriddha  9839323411
1                31           63       3     Manish  9874340113
2                31           99       5  Samriddha  9874168652
3                43           38       5     Manish  9864252889
4                89           98       5      Ishan  9864166467
5                70           70       4  Samriddha  9838336446
6                38           39       4      Ishan  9806614065
7                38           98       5  Samriddha  9879884445
8                88           98       4      Ishan  9869507556
9                88           47       3     Manish  9896293519

             email completion_status
0  user0@gmail.com           Ongoing
1  user1@gmail.com         Completed
2  user2@gmail.com         Completed
3  user3@gmail.com           Ongoing
4  user4@gmail.com           Ongoing
5  user5@gmail.com         Completed
6  user6@gmail.com         Completed
7  user7@gmail.com         Completed
8  user8@gmail.com         Completed
9  user9@gmail.com         Completed

In [7]:
print(dd.tail(10))

     student_id student_name             course        city  age  gender  \
340         341         Hari  Digital Marketing  Biratnagar   31  Female
341         342         Gita            Flutter  Biratnagar   32  Female
342         343        Aarav              UI/UX     Itahari   18    Male
343         344         Gita  Python with AI/ML   Kathmandu   33    Male
344         345         Gita  Digital Marketing     Pokhara   29    Male
345         346         Hari              UI/UX      Dharan   21  Female
346         347       Anisha  Digital Marketing  Biratnagar   31  Female
347         348         Sita            Flutter  Biratnagar   19    Male
348         349       Anisha              UI/UX     Itahari   27    Male
349         350         Hari  Python with AI/ML      Dharan   19  Female

    enrollment_date  course_fee  discount payment_status  attendance_percent  \
340      2026-06-10        5000        20        Pending                96.0
341      2026-04-16        5000        10           Paid                54.0
342      2026-03-01        7000        10           Paid                45.0
343      2026-05-07        5000        20           Paid                67.0
344      2026-05-18       10000        10           Paid                71.0
345      2026-06-17       10000        20           Paid                98.0
346      2026-03-21        5000        10           Paid                45.0
347      2026-02-05        5000        20           Paid                80.0
348      2026-05-05        5000        10           Paid                63.0
349      2026-04-04        5000        20        Pending                84.0

     assignment_score  final_score  rating     mentor       phone  \
340                38           71       5      Ishan  9831430348
341                33           61       5      Ishan  9865928299
342                85           46       5     Manish  9832055006
343                57           30       4  Samriddha  9828498406
344                45           89       4     Manish  9847970014
345                87           56       5  Samriddha  9873827203
346                51           44       3  Samriddha  9864328504
347                89           39       5  Samriddha  9821459197
348                58           52       5      Ishan  9862269669
349                57           62       3     Manish  9803556080

                 email completion_status
340  user340@gmail.com           Ongoing
341  user341@gmail.com           Ongoing
342  user342@gmail.com         Completed
343  user343@gmail.com           Ongoing
344  user344@gmail.com         Completed
345  user345@gmail.com           Ongoing
346  user346@gmail.com           Ongoing
347  user347@gmail.com         Completed
348  user348@gmail.com         Completed
349  user349@gmail.com           Ongoing

In [14]:
dd.shape

(350, 18)

In [15]:
print(dd.columns)

Index(['student_id', 'student_name', 'course', 'city', 'age', 'gender',
       'enrollment_date', 'course_fee', 'discount', 'payment_status',
       'attendance_percent', 'assignment_score', 'final_score', 'rating',
       'mentor', 'phone', 'email', 'completion_status'],
      dtype='str')

In [16]:
print(dd.dtypes)

student_id              int64
student_name              str
course                    str
city                      str
age                     int64
gender                    str
enrollment_date           str
course_fee              int64
discount                int64
payment_status            str
attendance_percent    float64
assignment_score        int64
final_score             int64
rating                  int64
mentor                    str
phone                     str
email                     str
completion_status         str
dtype: object

In [18]:
num_cols = [
    "age",
    "course_fee",
    "discount",
    "attendance_percent",
    "assignment_score",
    "final_score",
    "rating"
]

print(dd[num_cols].describe())

              age     course_fee    discount  attendance_percent  \
count  350.000000     350.000000  350.000000          349.000000
mean    26.174286   10085.711429    9.600000           70.154728
std      5.485686   53109.214627    7.929489           16.697929
min     17.000000   -5000.000000    0.000000           40.000000
25%     21.000000    5000.000000    0.000000           58.000000
50%     27.000000    7000.000000   10.000000           70.000000
75%     31.000000   10000.000000   20.000000           83.000000
max     35.000000  999999.000000   20.000000          100.000000

       assignment_score  final_score      rating
count        350.000000   350.000000  350.000000
mean          67.011429    65.011429    3.960000
std           20.686773    20.556718    0.817852
min           -5.000000    30.000000    3.000000
25%           51.000000    47.000000    3.000000
50%           69.000000    65.000000    4.000000
75%           85.750000    82.000000    5.000000
max          100.000000   100.000000    5.000000

In [22]:
dd.duplicated().sum()
dd = dd.drop_duplicates()

np.int64(0)

In [17]:
dd.isnull().sum()
num_cols = dd.select_dtypes(include=["int64","float64"]).columns
for col in num_cols:
    dd[col] = dd[col].fillna(dd[col].mean())
    text_cols = dd.select_dtypes(include=["object", "string"]).columns

for col in text_cols:
    dd[col] = dd[col].fillna(dd[col].mode()[0])

student_id            0
student_name          0
course                0
city                  0
age                   0
gender                0
enrollment_date       0
course_fee            0
discount              0
payment_status        0
attendance_percent    0
assignment_score      0
final_score           0
rating                0
mentor                0
phone                 0
email                 0
completion_status     0
dtype: int64

In [28]:
dd["enrollment_date"] = pd.to_datetime(dd["enrollment_date"], errors="coerce")


numeric_columns = [
    "course_fee",
    "discount",
    "attendance_percent",
    "assignment_score",
    "final_score",
    "rating",
    "age"
]

for col in numeric_columns:
    dd[col] = pd.to_numeric(dd[col], errors="coerce")
    
for col in text_cols:
    dd[col] = (
        dd[col]
        .astype(str)
        .str.strip()
        .str.title()
    ) 

negative_columns = [
    "course_fee",
    "attendance_percent",
    "assignment_score",
    "final_score",
    "age",
    "discount",
    "rating"
]

for col in negative_columns:
    dd[col] = dd[col].astype(float)

    mean_value = dd.loc[dd[col] >= 0, col].mean()

    dd.loc[dd[col] < 0, col] = mean_value

Data Cleaning Completed!

In [34]:
columns = [
    "course_fee",
    "attendance_percent",
    "assignment_score",
    "final_score"
]

outliers = {}

for col in columns:

    Q1 = dd[col].quantile(0.25)
    Q3 = dd[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

 


    outlier_rows = dd[(dd[col] < lower) | (dd[col] > upper)]

    outliers[col] = (lower, upper)



dd_remove = dd.copy()

for col in columns:

    lower, upper = outliers[col]

    dd_remove = dd_remove[
        (dd_remove[col] >= lower) &
        (dd_remove[col] <= upper)
    ]


print(dd_remove.shape)



dd_median = dd.copy()

for col in columns:

    lower, upper = outliers[col]

    median = dd[col].median()

    dd_median.loc[
        (dd_median[col] < lower) |
        (dd_median[col] > upper),
        col
    ] = median





dd_clip = dd.copy()

for col in columns:

    lower, upper = outliers[col]

    dd_clip[col] = dd_clip[col].clip(lower, upper)



z_columns = [
    "course_fee",
    "attendance_percent",
    "assignment_score",
    "final_score"
]

for col in z_columns:

    mean = dd[col].mean()
    std = dd[col].std()

    dd[col + "_zscore"] = (dd[col] - mean) / std

    outliers = dd[(dd[col + "_zscore"] > 3) | (dd[col + "_zscore"] < -3)]
outliers

(349, 22)

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status, course_fee_zscore, attendance_percent_zscore, assignment_score_zscore, final_score_zscore]
Index: []

[0 rows x 22 columns]