In [42]:
import pandas as pd

In [43]:
dd=pd.read_csv("datasets/bad_daraz_dataset.csv")

In [44]:
dd["price"]=pd.to_numeric(dd["price"],errors="coerce")

In [48]:
mean=dd["price"].mean()


std=dd["price"].std()
dd["z_score"]=(dd["price"]-mean)/std #z-score
outliers=dd[dd["z_score"].abs()>2]
outliers

# mean
# std

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,z_score
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.245633
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120,2.245633

In [34]:
Q1=dd["price"].quantile(0.25)
Q3=dd["price"].quantile(0.75)
MD=dd["price"].median()

# Q1
# Q3
IQR=Q3-Q1
# IQR
lb=Q1-(1.5*IQR)#lower bound
ub=Q3+(1.5*IQR)#upper bound
# lb
# ub
MD

np.float64(2500.0)

In [28]:
dd.loc[(dd["price"]<lb) | (dd["price"]>ub),"price"]=MD
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,2500.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,2500.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,10,Haha,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
12,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
14,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [21]:
outliers=dd[(dd["price"]<lb) | (dd["price"]>ub)]
outliers
len(outliers)

2

In [22]:
dd["price"].clip(lb,ub) #in outliers it sets the value from lower bound and upper bound whichever is the closest

0     8250.0
1        NaN
2     3500.0
3     1500.0
4     5500.0
5     4200.0
6     8250.0
7        NaN
8     1800.0
9     1800.0
10    2500.0
11    2500.0
12     800.0
13   -2500.0
14   -2500.0
Name: price, dtype: float64